version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
    - .:/app
    command: sh -c "PORT=4000 yarn start"
    ports:
    - "4000:4000"